### ISSUE TITLE
Couldn't load the irb library 'boson/console': SyntaxError

### ISSUE THREAD

**Issue by tymat** [cldwalker/boson-more#5]
Couldn't load the irb library 'boson/console': SyntaxError
* /var/www/gcr_ordering/shared/bundle/ruby/2.2.0/gems/boson-more-0.3.0/lib/boson/repo_index.rb:38: syntax error, unexpected keyword_do_cond, expecting ':'
        File.open(marshal_file, 'rb') do |f|
                                        ^
/var/www/gcr_ordering/shared/bundle/ruby/2.2.0/gems/boson-more-0.3.0/lib/boson/repo_index.rb:41: syntax error, unexpected ':', expecting keyword_end
        end : [[], [], {}]
             ^
/var/www/gcr_ordering/shared/bundle/ruby/2.2.0/gems/boson-more-0.3.0/lib/boson/repo_index.rb:73: syntax error, unexpected keyword_do_cond, expecting keyword_end
      File.open(marshal_file, rdwr_access) do |f|
                                             ^
/var/www/gcr_ordering/shared/bundle/ruby/2.2.0/gems/boson-more-0.3.0/lib/boson/repo_index.rb:134: syntax error, unexpected keyword_end, expecting end-of-input
* /var/www/gcr_ordering/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
Loading production environment (Rails 4.1.5)

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 13 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/boson-more#5). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
Fixed in #4

**Comment by cldwalker** [comment]
0.3.1 released with fix
